name : Python application test with Github Actions

on: 
  push:
    branches: main

jobs: 
  build:
    runs-on : ubuntu-latest
    steps :
    - uses : actions/checkout@v3
    - name : Set up Python 3.11
      uses : actions/setup-python@v1
      with : 
        python-version : 3.11
    - name : install dependencies 
      run : | 
        make install
    - name : Format code
      run : |
        make format   
    - name : Lint with pylint
      run : | 
        make lint
    - name : Test with pytest
      run : |
        make test
    - name : login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_PWD}}
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v2
      with: 
        context: .
        push : true
        tags: mhkaaniche/Python_Web_App_Docker:latest, mhkaaniche/Python_Web_App_Docker:${{ github.run_number }}
  



